# Generated by Django 5.0.3 on 2024-03-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubiertas', '0002_alter_cubiertas_image_alter_cubiertas_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cubiertas',
            new_name='Decks',
        ),
    ]
