# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubiertas', '0004_cubiertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubiertas',
            name='title',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='title',
        ),
    ]
