# Generated by Django 5.0.3 on 2024-03-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carpinterias',
            new_name='Carpentry',
        ),
    ]
