# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteria', '0003_carpinterias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpentry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='carpinterias',
            name='title',
        ),
    ]
