# Generated by Django 5.0.3 on 2024-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotanos', '0002_alter_sotanos_image_alter_sotanos_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sotanos',
            new_name='Basement',
        ),
    ]
