# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotanos', '0004_sotanos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sotanos',
            name='title',
        ),
    ]
