# Generated by Django 5.0.3 on 2024-03-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nieve', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nieve',
            new_name='Snow',
        ),
    ]
