# Generated by Django 5.0.2 on 2024-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image_remove_post_video_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='Upload any file.', null=True, upload_to='blog/media/%Y'),
        ),
    ]
