# Generated by Django 5.0.2 on 2024-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/video/%Y'),
        ),
    ]
