# Generated by Django 5.0.3 on 2024-03-04 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_media_file_post_image_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('date', models.DateField(default=datetime.date.today)),
                ('video', models.FileField(blank=True, null=True, upload_to='blog/video/%Y')),
            ],
        ),
    ]
