# Generated by Django 5.0.3 on 2024-03-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_date_remove_post_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
