# Generated by Django 5.0.2 on 2024-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puertaventana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puertaventanas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puertaventana/images'),
        ),
        migrations.AlterField(
            model_name='puertaventanas',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='puertaventana/video/%Y'),
        ),
    ]
