# Generated by Django 5.0.3 on 2024-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puertaventana', '0002_alter_puertaventanas_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puertaventanas',
            new_name='doorswindows',
        ),
    ]
