# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puertaventana', '0004_puertaventanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorswindows',
            name='title',
        ),
        migrations.RemoveField(
            model_name='puertaventanas',
            name='title',
        ),
    ]
