# Generated by Django 5.0.2 on 2024-03-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demolicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolicion',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
