# Generated by Django 5.0.3 on 2024-03-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demolicion', '0002_alter_demolicion_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demolicion',
            new_name='Demolition',
        ),
    ]
