# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demolicion', '0004_demolicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demolicion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='demolition',
            name='title',
        ),
    ]
