# Generated by Django 5.0.3 on 2024-03-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molduras', '0002_alter_molduras_image_alter_molduras_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Molduras',
            new_name='Moldings',
        ),
    ]
