# Generated by Django 5.0.3 on 2024-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molduras', '0004_molduras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moldings',
            name='title',
        ),
        migrations.RemoveField(
            model_name='molduras',
            name='title',
        ),
    ]
